import { ConsoleId, ConsoleMeta, GameItem, CrtSettings } from '../types';
import { getRetroGameCover } from './gameArt';

export const CONSOLES: Record<ConsoleId, ConsoleMeta> = {
  nes: {
    id: 'nes',
    name: 'Nintendo Entertainment System',
    shortName: 'NES',
    generation: '3rd Gen (1983)',
    year: 1983,
    color: '#ef4444',
    badgeBg: 'bg-red-500/10 text-red-400 border-red-500/30',
    borderColor: 'border-red-500',
    glowColor: 'rgba(239, 68, 68, 0.4)',
    icon: 'Gamepad2',
    extensions: ['.nes'],
    coreName: 'fceumm',
    ejsCore: 'nes',
    nativeAspect: '4:3',
  },
  snes: {
    id: 'snes',
    name: 'Super Nintendo Entertainment System',
    shortName: 'SNES',
    generation: '4th Gen (1990)',
    year: 1990,
    color: '#a855f7',
    badgeBg: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    borderColor: 'border-purple-500',
    glowColor: 'rgba(168, 85, 247, 0.4)',
    icon: 'Tv',
    extensions: ['.smc', '.sfc', '.fig'],
    coreName: 'snes9x',
    ejsCore: 'snes',
    nativeAspect: '4:3',
  },
  gb: {
    id: 'gb',
    name: 'Game Boy',
    shortName: 'GB',
    generation: '4th Gen (1989)',
    year: 1989,
    color: '#84cc16',
    badgeBg: 'bg-lime-500/10 text-lime-400 border-lime-500/30',
    borderColor: 'border-lime-500',
    glowColor: 'rgba(132, 204, 22, 0.4)',
    icon: 'Smartphone',
    extensions: ['.gb'],
    coreName: 'gambatte',
    ejsCore: 'gb',
    nativeAspect: '10:9',
  },
  gbc: {
    id: 'gbc',
    name: 'Game Boy Color',
    shortName: 'GBC',
    generation: '5th Gen (1998)',
    year: 1998,
    color: '#06b6d4',
    badgeBg: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
    borderColor: 'border-cyan-500',
    glowColor: 'rgba(6, 182, 212, 0.4)',
    icon: 'Sparkles',
    extensions: ['.gbc'],
    coreName: 'gambatte',
    ejsCore: 'gb',
    nativeAspect: '10:9',
  },
  gba: {
    id: 'gba',
    name: 'Game Boy Advance',
    shortName: 'GBA',
    generation: '6th Gen (2001)',
    year: 2001,
    color: '#3b82f6',
    badgeBg: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
    borderColor: 'border-blue-500',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    icon: 'Radio',
    extensions: ['.gba'],
    coreName: 'mgba',
    ejsCore: 'gba',
    nativeAspect: '3:2',
  },
  genesis: {
    id: 'genesis',
    name: 'Sega Genesis / Mega Drive',
    shortName: 'Genesis',
    generation: '4th Gen (1988)',
    year: 1988,
    color: '#0ea5e9',
    badgeBg: 'bg-sky-500/10 text-sky-400 border-sky-500/30',
    borderColor: 'border-sky-500',
    glowColor: 'rgba(14, 165, 233, 0.4)',
    icon: 'Disc',
    extensions: ['.md', '.bin', '.gen', '.smd'],
    coreName: 'genesis_plus_gx',
    ejsCore: 'segaMD',
    nativeAspect: '4:3',
  },
  n64: {
    id: 'n64',
    name: 'Nintendo 64',
    shortName: 'N64',
    generation: '5th Gen (1996)',
    year: 1996,
    color: '#eab308',
    badgeBg: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30',
    borderColor: 'border-yellow-500',
    glowColor: 'rgba(234, 179, 8, 0.4)',
    icon: 'Box',
    extensions: ['.z64', '.n64', '.v64'],
    coreName: 'mupen64plus_next',
    ejsCore: 'n64',
    nativeAspect: '4:3',
  },
  ps1: {
    id: 'ps1',
    name: 'PlayStation 1',
    shortName: 'PS1',
    generation: '5th Gen (1994)',
    year: 1994,
    color: '#ec4899',
    badgeBg: 'bg-pink-500/10 text-pink-400 border-pink-500/30',
    borderColor: 'border-pink-500',
    glowColor: 'rgba(236, 72, 153, 0.4)',
    icon: 'Disc3',
    extensions: ['.chd', '.cue', '.iso', '.pbp'],
    coreName: 'mednafen_psx_hw',
    ejsCore: 'psx',
    nativeAspect: '4:3',
  },
  ps2: {
    id: 'ps2',
    name: 'PlayStation 2',
    shortName: 'PS2',
    generation: '6th Gen (2000)',
    year: 2000,
    color: '#6366f1',
    badgeBg: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/30',
    borderColor: 'border-indigo-500',
    glowColor: 'rgba(99, 102, 241, 0.4)',
    icon: 'Disc3',
    extensions: ['.iso', '.cso', '.chd', '.isz', '.elf'],
    coreName: 'play',
    ejsCore: '',
    emulator: 'playjs',
    nativeAspect: '4:3',
  },
};

export const DEFAULT_CRT_SETTINGS: CrtSettings = {
  enabled: true,
  scanlineMode: 'medium',
  curvature: true,
  flicker: true,
  chromaticAberration: true,
  phosphorGrid: true,
  colorPreset: 'standard',
  bloom: true,
  vignette: true,
};

export const INITIAL_DEMO_GAMES: GameItem[] = [
  {
    id: 'demo-retro-pilot',
    title: 'Retro Pilot: Star Vanguard',
    consoleId: 'snes',
    year: 1993,
    genre: 'Shoot Em Up',
    coverUrl: getRetroGameCover('snes', 'Retro Pilot: Star Vanguard', 'Shoot Em Up'),
    description: 'High-speed vertical space shooter featuring Mode 7 pseudo-3D parallax planetary descent and multi-stage boss encounters.',
    favorite: true,
    lastPlayed: new Date(Date.now() - 3600000 * 2).toISOString(),
    playTimeMinutes: 48,
    saveStatesCount: 3,
    isDemo: true,
  },
  {
    id: 'demo-cyber-quest',
    title: 'Cyber Quest Chronicles',
    consoleId: 'nes',
    year: 1989,
    genre: 'Action RPG',
    coverUrl: getRetroGameCover('nes', 'Cyber Quest Chronicles', 'Action RPG'),
    description: 'Legendary 8-bit platforming odyssey across neo-futuristic dungeons, power-up relics, and secret warp zones.',
    favorite: true,
    lastPlayed: new Date(Date.now() - 3600000 * 24).toISOString(),
    playTimeMinutes: 120,
    saveStatesCount: 5,
    isDemo: true,
  },
  {
    id: 'demo-emerald-speedway',
    title: 'Emerald Speedway GP',
    consoleId: 'gba',
    year: 2002,
    genre: 'Racing',
    coverUrl: getRetroGameCover('gba', 'Emerald Speedway GP', 'Racing'),
    description: 'Handheld 32-bit kart racer loaded with boost drift mechanics, obstacle courses, and time trial cups.',
    favorite: false,
    lastPlayed: new Date(Date.now() - 3600000 * 48).toISOString(),
    playTimeMinutes: 35,
    saveStatesCount: 1,
    isDemo: true,
  },
  {
    id: 'demo-monochrome-monk',
    title: 'Pocket Monastery: Green Edition',
    consoleId: 'gb',
    year: 1991,
    genre: 'Puzzle Adventure',
    coverUrl: getRetroGameCover('gb', 'Pocket Monastery: Green Edition', 'Puzzle Adventure'),
    description: '4-shade green olive LCD dungeon escape requiring clever box pushing, trap dodging, and ancient talisman gathering.',
    favorite: false,
    playTimeMinutes: 15,
    saveStatesCount: 0,
    isDemo: true,
  },
  {
    id: 'demo-genesis-brawler',
    title: 'Sonic Street Strike',
    consoleId: 'genesis',
    year: 1992,
    genre: 'Beat Em Up',
    coverUrl: getRetroGameCover('genesis', 'Sonic Street Strike', 'Beat Em Up'),
    description: '16-bit Blast Processing powerhouse delivering lightning-fast combat combos and pumping FM synthesizer soundtrack.',
    favorite: true,
    playTimeMinutes: 62,
    saveStatesCount: 2,
    isDemo: true,
  },
  {
    id: 'demo-n64-poly-drift',
    title: 'Apex Altitude 64',
    consoleId: 'n64',
    year: 1997,
    genre: '3D Sports',
    coverUrl: getRetroGameCover('n64', 'Apex Altitude 64', '3D Sports'),
    description: 'First-generation 3D polygon stunt simulation taking full advantage of analog thumbstick steering and fog clipping.',
    favorite: false,
    playTimeMinutes: 20,
    saveStatesCount: 1,
    isDemo: true,
  },
];
